### ISSUE TITLE
Bindings checklist

### ISSUE THREAD

**Issue by bryanchriswhite** [bryanchriswhite/python-libstorj#1]
_(checklist copied from [node-libstorj issue #15](https://github.com/Storj/node-libstorj/issues/15))_

These are functions in libstorj/src/storj.h to be bound:

- [x]  `int storj_mnemonic_generate(int strength, char **buffer)`
- [x]  `bool storj_mnemonic_check(const char *mnemonic)`
- [x]  `int storj_bridge_get_info(storj_env_t *env, void *handle, uv_after_work_cb cb)`
- [x]  `int storj_bridge_get_buckets(storj_env_t *env, void *handle, uv_after_work_cb cb)`
- [x]  `int storj_bridge_create_bucket(storj_env_t *env, const char *name, void *handle, uv_after_work_cb cb)`
- [x]  `int storj_bridge_delete_bucket(storj_env_t *env, const char *id, void *handle, uv_after_work_cb cb)`
- [x]  `int storj_bridge_list_files(storj_env_t *env, const char *id, void *handle, uv_after_work_cb cb)`
- [ ]  `int storj_bridge_delete_file(storj_env_t *env, const char *bucket_id, const char *file_id, void *handle, uv_after_work_cb cb)`
- [ ]  `int storj_bridge_store_file_cancel(storj_upload_state_t *state)`
- [ ]  `int storj_bridge_store_file(storj_env_t *env, storj_upload_state_t *state, storj_upload_opts_t *opts, void *handle, storj_progress_cb progress_cb, storj_finished_upload_cb finished_cb)`
- [ ]  `int storj_bridge_resolve_file_cancel(storj_download_state_t *state)`
- [ ]  `int storj_bridge_resolve_file(storj_env_t *env, storj_download_state_t *state, const char *bucket_id, const char *file_id, FILE *destination, void *handle, storj_progress_cb progress_cb, storj_finished_download_cb finished_cb)`

And additional:
- [ ]  `int storj_bridge_register(storj_env_t *env, const char *email, const char *password, void *handle, uv_after_work_cb cb)`
- [ ]  `int storj_bridge_get_bucket(storj_env_t *env, const char *id, void *handle, uv_after_work_cb cb)`
- [ ]  `uint64_t storj_util_timestamp()`
- [ ]  `int storj_bridge_get_file_info(storj_env_t *env, const char *bucket_id, const char *file_id, void *handle, uv_after_work_cb cb)`
- [ ]  `int storj_bridge_list_mirrors(storj_env_t *env, const char *bucket_id, const char *file_id, void *handle, uv_after_work_cb cb)`

**Comment by marcorosa** [comment]
Are those the functions to be bound? `libstorj` offers these apis, so I guess these are the functions that should be bound:
```
working with buckets and files:
  list-buckets
  list-files <bucket-id>
  remove-file <bucket-id> <file-id>
  remove-bucket <bucket-id>
  add-bucket <name> 
  list-mirrors <bucket-id> <file-id>
  get-bucket-id <bucket-name>

uploading files:
  upload-file <bucket-id> <path>

downloading files:
  download-file <bucket-id> <file-id> <path>

bridge api information:
  get-info
```

**Comment by marcorosa** [comment]
Are those the functions to be bound? `libstorj` offers these apis, so I guess these are the functions that should be bound:
```
working with buckets and files:
  list-buckets
  list-files <bucket-id>
  remove-file <bucket-id> <file-id>
  remove-bucket <bucket-id>
  add-bucket <name> 
  list-mirrors <bucket-id> <file-id>
  get-bucket-id <bucket-name>

uploading files:
  upload-file <bucket-id> <path>

downloading files:
  download-file <bucket-id> <file-id> <path>

bridge api information:
  get-info
```

**Comment by bryanchriswhite** [comment]
@marcorosa this issue is a duplicate of [storj/python-libstorj#1](https://github.com/Storj/python-libstorj/issues/1) and was not kept up to date. I've updated it but will close this issue here as the storj repo is where most people should interact with the python-libstorj repo (this is my development fork).

**Comment by bryanchriswhite** [comment]
To answer your question, yes; these are the functions to be bound in order for the library to really be considered usable.
